#spring:
#  datasource:
#    url: jdbc:h2:mem:traveldb
#    driverClassName: org.h2.Driver
#   username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect

kafka:
  bootstrap-servers: localhost:9092
  topic:
    pnr: travel-topic

server:
  ssl:
    key-store: enablehttpsspringboot.jks
    key-store-password: hari@510
    key-store-type: pkcs12
    key-alias: enablehttpsspringboot
    key-password: hari@510
  port: 9090